ALTER TABLE collaborator ALTER COLUMN document SET NOT NULL;
ALTER TABLE collaborator DROP COLUMN IF EXISTS status;
ALTER TABLE collaborator DROP COLUMN IF EXISTS email;

ALTER TABLE asset_type DROP COLUMN IF EXISTS description;
ALTER TABLE asset_type DROP COLUMN IF EXISTS icon;

ALTER TABLE sector DROP COLUMN IF EXISTS description;

ALTER TABLE branch DROP COLUMN IF EXISTS state;
ALTER TABLE branch DROP COLUMN IF EXISTS city;

ALTER TABLE company DROP COLUMN IF EXISTS state;
ALTER TABLE company DROP COLUMN IF EXISTS city;
