ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE USAGE, SELECT ON SEQUENCES FROM invtech_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM invtech_app;

REVOKE USAGE ON SCHEMA public FROM invtech_app;

DROP ROLE IF EXISTS invtech_app;

DROP EXTENSION IF EXISTS "pgcrypto";
DROP EXTENSION IF EXISTS "citext";
