ALTER TABLE collaborator DROP COLUMN IF EXISTS cargo;

ALTER TABLE asset
    DROP COLUMN IF EXISTS notes,
    DROP COLUMN IF EXISTS storage,
    DROP COLUMN IF EXISTS ram,
    DROP COLUMN IF EXISTS cpu,
    DROP COLUMN IF EXISTS model,
    DROP COLUMN IF EXISTS brand,
    DROP COLUMN IF EXISTS hostname;
